version: "3.1"

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    env_file:
      - .env
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ${NEXTCLOUD_CONFIG_VOLUME}:/config
      - ${NEXTCLOUD_DATA_VOLUME}:/data
    ports:
      - 9443:443
    depends_on:
      - "db"
    restart: unless-stopped

