---
- hosts: all

  vars_files:
    - "vaultfile.yml"

  tasks:
  - name: Install Python packages
    pip:
      name: 
        - docker

  - name: Create Docker network
    docker_network:
      name: nextcloud_network

  - name: Run PostgreSQL container
    docker_container:
      name: postgres
      hostname: postgres
      image: postgres
      networks:
        - name: nextcloud_network
      restart: yes
      restart_policy: always
      env:
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      volumes:
        - "{{ POSTGRES_DATA_VOLUME }}:/var/lib/postgresql/data"

  - name: Run adminer container 
    docker_container:
      name: adminer
      image: adminer
      networks:
        - name: nextcloud_network
      restart: yes
      ports:
        - 8080:8080

  - name: Run nextcloud container
    docker_container:
      name: nextcloud
      image: linuxserver/nextcloud
      networks:
        - name: nextcloud_network
      restart: yes
      restart_policy: unless-stopped
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "{{ timezone }}"
      volumes:
        - "{{ NEXTCLOUD_CONFIG_VOLUME }}:/config"
        - "{{ NEXTCLOUD_DATA_VOLUME }}:/data"
      ports:
        - 9443:443
